---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  talk:
    default_front_matter_template: talk
  publication:
    default_front_matter_template: publication
  project:
    default_front_matter_template: project
  post:
    default_front_matter_template: post
  home:
    default_front_matter_template: home
upload_dir: ''
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.38.1
