---
upload_path: "/static/img/img/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  talk:
    default_front_matter_template: talk
  publication:
    default_front_matter_template: publication
  project:
    default_front_matter_template: project
  post:
    default_front_matter_template: post
  home:
    default_front_matter_template: home
version: 0.38.1
