---
hide_body: false
is_partial: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: summary
  label: Summary
  type: text
  hidden: false
  default: ''
- name: image_preview
  label: Image preview
  type: file
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: external_link
  label: External link
  type: text
  hidden: false
  default: ''
- name: math
  label: Math
  type: boolean
  hidden: false
  default: false
- name: header
  label: Header
  type: field_group
  fields:
  - name: image
    label: Image
    type: file
    hidden: false
    default: ''
  - name: caption
    label: Caption
    type: text
    hidden: false
    default: ''
  hidden: false
  default: 
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
- name: highlight
  label: Highlight
  type: boolean
  hidden: false
  default: true
